AWSTemplateFormatVersion: 2010-09-09

Transform:
- AWS::Serverless-2016-10-31

Parameters: 
  ParamApiKey: 
    Type: String
    Description: netcup API key
  ParamApiSecret: 
    Type: String
    Description: netcup API key secret
  ParamCustomer: 
    Type: String
    Description: netcup customer id
  ParamCustomDomain: 
    Type: String
    Description: custom domain name for API

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./api.yml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref DdnsServiceFunction

  Api:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body:
        swagger: 2.0
        info:
          title: !Ref AWS::StackName
        paths:
          "/{proxy+}":
            x-amazon-apigateway-any-method:
              produces:
                - application/json
              parameters:
                - name: proxy
                  in: path
                  required: true
                  type: string
              responses: {}
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: '200'
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DdnsServiceFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                cacheNamespace: roq9wj
                cacheKeyParameters:
                  - method.request.path.proxy
                type: aws_proxy
      Description: A test API
      Name: !Ref AWS::StackName

  DdnsDomain:
    Type: AWS::ApiGateway::DomainName
    Properties: 
      CertificateArn: arn:aws:acm:us-east-1:840940990295:certificate/3dd20275-c16a-48f2-b141-d9a47eb1625f
      DomainName: 
        Ref: ParamCustomDomain

  PathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: api
      DomainName: !Ref DdnsDomain
      RestApiId: !Ref Api
      Stage: prod

  DdnsServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ncddns.handler
      Runtime: provided
      CodeUri: ../target/function.zip
      Layers:
      - arn:aws:lambda:eu-central-1:744348701589:layer:bash:8
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Environment:
        Variables:
          VERBOSE: false
          apikey: 
            Ref: ParamApiKey
          apipw: 
            Ref: ParamApiSecret
          cid: 
            Ref: ParamCustomer
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

  DdnsServiceFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DdnsServiceFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*

Outputs:
  LambdaEndpoint:
    Description: API Gateway URL of the Lambda Function
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod/"