AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: netcup dyndns
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:
  E2cNativeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ncddns.handler
      Runtime: provided
      CodeUri: ../target/function.zip
      Layers:
      - arn:aws:lambda:eu-central-1:744348701589:layer:bash:8
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Environment:
        Variables:
          VERBOSE: false
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  E2cNativeApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: E2cNativeApi
